name: 'Yet another Hugo setup action'
description: "GitHub Action for Hugo, the world's fastest framework for building websites"
author: 'frenchvandal'
branding:
  color: 'orange'
  icon: 'cloud'

inputs:
  version:
    description: 'Hugo version'
    default: 'latest'
    required: false
  extended:
    description: 'Use Hugo extended'
    default: 'false'
    required: false
  args:
    description: 'Arguments to pass to Hugo'
    default: 'version'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
